### ISSUE TITLE
Postgres: Container name collisions on threaded tests

### ISSUE THREAD

**Issue by 0xDEC0DE** [juledwar/db-testtools#5]
Every so often, running a multi-threaded test will throw an exception like the following:

```
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=testdb-434: Conflict ("Conflict. The container name "/testdb-434" is already in use by container "a8ea9". You have to remove (or rename) that container to be able to reuse that name.")
```

Hilarity ensues.

# Steps to reproduce

Unknown.

# Errata

Spawning PostgreSQL containers attempts to make a "UUID" by selecting a random number between 1 and 1000, and does no existence checking before trying to use it.  With a surface that small, collisions are bound to be relatively common.

**Comment by 0xDEC0DE** [comment]
Applied this change, and ran a multi-threaded test I have that has been known to collide fairly often, 100 times without issue.

Considering this one squashed.

**Comment by juledwar** [comment]
I'll drop a release out soon.
